export interface District {
  name: string;
  cities: string[];
}

export interface State {
  name: string;
  districts: District[];
}

export const INDIA_LOCATIONS: State[] = [
  {
    name: 'Andhra Pradesh',
    districts: [
      { name: 'Anantapur', cities: ['Anantapur', 'Guntakal', 'Dharmavaram', 'Hindupur', 'Kadiri'] },
      { name: 'Chittoor', cities: ['Chittoor', 'Tirupati', 'Madanapalle', 'Srikalahasti', 'Puttur'] },
      { name: 'East Godavari', cities: ['Kakinada', 'Rajahmundry', 'Amalapuram', 'Samalkot', 'Pithapuram'] },
      { name: 'Guntur', cities: ['Guntur', 'Tenali', 'Narasaraopet', 'Mangalagiri', 'Ponnur'] },
      { name: 'Krishna', cities: ['Vijayawada', 'Machilipatnam', 'Gudivada', 'Nuzvid', 'Nandigama'] },
      { name: 'Kurnool', cities: ['Kurnool', 'Nandyal', 'Adoni', 'Yemmiganur', 'Dhone'] },
      { name: 'Nellore', cities: ['Nellore', 'Kavali', 'Gudur', 'Sullurpeta', 'Venkatagiri'] },
      { name: 'Prakasam', cities: ['Ongole', 'Chirala', 'Kandukur', 'Markapur', 'Giddalur'] },
      { name: 'Srikakulam', cities: ['Srikakulam', 'Narasannapeta', 'Tekkali', 'Palasa', 'Amadalavalasa'] },
      { name: 'Visakhapatnam', cities: ['Visakhapatnam', 'Bheemunipatnam', 'Anakapalle', 'Gajuwaka', 'Narsipatnam'] },
      { name: 'Vizianagaram', cities: ['Vizianagaram', 'Bobbili', 'Parvathipuram', 'Salur', 'Gajapathinagaram'] },
      { name: 'West Godavari', cities: ['Eluru', 'Bhimavaram', 'Tadepalligudem', 'Narsapuram', 'Palakol'] },
      { name: 'YSR Kadapa', cities: ['Kadapa', 'Proddatur', 'Rajampet', 'Jammalamadugu', 'Badvel'] },
    ],
  },
  {
    name: 'Arunachal Pradesh',
    districts: [
      { name: 'Itanagar Capital Region', cities: ['Itanagar', 'Naharlagun', 'Nirjuli', 'Banderdewa'] },
      { name: 'East Siang', cities: ['Pasighat', 'Namsing', 'Mebo'] },
      { name: 'West Siang', cities: ['Aalo', 'Mechuka', 'Yomcha'] },
      { name: 'Tawang', cities: ['Tawang', 'Jang', 'Lumla'] },
      { name: 'Lohit', cities: ['Tezu', 'Namsai', 'Wakro'] },
      { name: 'Changlang', cities: ['Changlang', 'Bordumsa', 'Miao'] },
    ],
  },
  {
    name: 'Assam',
    districts: [
      { name: 'Kamrup Metropolitan', cities: ['Guwahati', 'Dispur', 'Jalukbari', 'Azara', 'Beltola'] },
      { name: 'Kamrup', cities: ['Rangia', 'Barpeta Road', 'Mirza', 'Palashbari'] },
      { name: 'Dibrugarh', cities: ['Dibrugarh', 'Chabua', 'Naharkatia', 'Duliajan'] },
      { name: 'Jorhat', cities: ['Jorhat', 'Mariani', 'Titabor', 'Teok'] },
      { name: 'Nagaon', cities: ['Nagaon', 'Hojai', 'Lumding', 'Doboka'] },
      { name: 'Tinsukia', cities: ['Tinsukia', 'Digboi', 'Margherita', 'Doomdooma'] },
      { name: 'Sonitpur', cities: ['Tezpur', 'Dhekiajuli', 'Rangapara', 'Gohpur'] },
      { name: 'Cachar', cities: ['Silchar', 'Sonai', 'Lakhipur', 'Katlicherra'] },
      { name: 'Barpeta', cities: ['Barpeta', 'Sarthebari', 'Pathsala', 'Baihata'] },
      { name: 'Goalpara', cities: ['Goalpara', 'Dudhnoi', 'Lakhipur', 'Matia'] },
      { name: 'Sibsagar', cities: ['Sibsagar', 'Amguri', 'Nazira', 'Sonari'] },
      { name: 'Dhubri', cities: ['Dhubri', 'Gauripur', 'Bilasipara', 'Agomoni'] },
    ],
  },
  {
    name: 'Bihar',
    districts: [
      { name: 'Patna', cities: ['Patna', 'Danapur', 'Hajipur', 'Phulwari Sharif', 'Barh'] },
      { name: 'Gaya', cities: ['Gaya', 'Bodh Gaya', 'Sherghati', 'Tekari', 'Dobhi'] },
      { name: 'Muzaffarpur', cities: ['Muzaffarpur', 'Kanti', 'Sitamarhi', 'Motipur'] },
      { name: 'Bhagalpur', cities: ['Bhagalpur', 'Naugachhia', 'Sultanganj', 'Banka'] },
      { name: 'Darbhanga', cities: ['Darbhanga', 'Laheriasarai', 'Birpur', 'Jale'] },
      { name: 'Purnia', cities: ['Purnia', 'Katihar', 'Araria', 'Kishanganj'] },
      { name: 'Begusarai', cities: ['Begusarai', 'Barauni', 'Teghra', 'Bihat'] },
      { name: 'Munger', cities: ['Munger', 'Jamalpur', 'Khagaria', 'Lakhisarai'] },
      { name: 'Nalanda', cities: ['Bihar Sharif', 'Rajgir', 'Hilsa', 'Islampur'] },
      { name: 'Saran', cities: ['Chhapra', 'Revelganj', 'Sonepur', 'Marhaura'] },
      { name: 'Vaishali', cities: ['Hajipur', 'Lalganj', 'Mahua', 'Patepur'] },
      { name: 'East Champaran', cities: ['Motihari', 'Raxaul', 'Chakia', 'Pakridayal'] },
      { name: 'West Champaran', cities: ['Bettiah', 'Bagaha', 'Narkatiaganj', 'Valmiki Nagar'] },
      { name: 'Samastipur', cities: ['Samastipur', 'Dalsinghsarai', 'Rosera', 'Pusa'] },
      { name: 'Sitamarhi', cities: ['Sitamarhi', 'Dumra', 'Pupri', 'Riga'] },
      { name: 'Madhubani', cities: ['Madhubani', 'Jainagar', 'Jhanjharpur', 'Phulparas'] },
      { name: 'Supaul', cities: ['Supaul', 'Birpur', 'Nirmali', 'Triveniganj'] },
      { name: 'Arwal', cities: ['Arwal', 'Kurtha', 'Kaler'] },
      { name: 'Aurangabad', cities: ['Aurangabad', 'Daudnagar', 'Obra', 'Rafiganj'] },
      { name: 'Buxar', cities: ['Buxar', 'Dumraon', 'Brahmpur', 'Itarhi'] },
      { name: 'Kaimur', cities: ['Bhabua', 'Mohania', 'Kudra', 'Adhaura'] },
      { name: 'Rohtas', cities: ['Sasaram', 'Dehri', 'Bikramganj', 'Nasriganj'] },
      { name: 'Jehanabad', cities: ['Jehanabad', 'Makhdumpur', 'Ghoshi', 'Hulasganj'] },
    ],
  },
  {
    name: 'Chhattisgarh',
    districts: [
      { name: 'Raipur', cities: ['Raipur', 'Durg', 'Bhilai', 'Arang', 'Abhanpur'] },
      { name: 'Bilaspur', cities: ['Bilaspur', 'Korba', 'Akaltara', 'Mungeli'] },
      { name: 'Durg', cities: ['Durg', 'Bhilai', 'Bhilai-3', 'Risali', 'Jamul'] },
      { name: 'Rajnandgaon', cities: ['Rajnandgaon', 'Dongargarh', 'Khairagarh', 'Ambagarh Chowki'] },
      { name: 'Raigarh', cities: ['Raigarh', 'Sarangarh', 'Gharghoda', 'Lailunga'] },
      { name: 'Jagdalpur', cities: ['Jagdalpur', 'Kondagaon', 'Narayanpur', 'Dantewada'] },
      { name: 'Ambikapur', cities: ['Ambikapur', 'Baikunthpur', 'Premnagar', 'Rampur'] },
      { name: 'Jashpur', cities: ['Jashpur Nagar', 'Kunkuri', 'Pathalgaon', 'Bagicha'] },
    ],
  },
  {
    name: 'Goa',
    districts: [
      { name: 'North Goa', cities: ['Panaji', 'Mapusa', 'Calangute', 'Candolim', 'Pernem'] },
      { name: 'South Goa', cities: ['Margao', 'Vasco da Gama', 'Ponda', 'Canacona', 'Quepem'] },
    ],
  },
  {
    name: 'Gujarat',
    districts: [
      { name: 'Ahmedabad', cities: ['Ahmedabad', 'Gandhinagar', 'Naroda', 'Sanand', 'Dholka'] },
      { name: 'Surat', cities: ['Surat', 'Bardoli', 'Olpad', 'Mandvi', 'Vyara'] },
      { name: 'Vadodara', cities: ['Vadodara', 'Anand', 'Padra', 'Karjan', 'Savli'] },
      { name: 'Rajkot', cities: ['Rajkot', 'Gondal', 'Jetpur', 'Wankaner', 'Morbi'] },
      { name: 'Bhavnagar', cities: ['Bhavnagar', 'Sihor', 'Palitana', 'Talaja', 'Mahuva'] },
      { name: 'Jamnagar', cities: ['Jamnagar', 'Dwarka', 'Khambhalia', 'Kalavad', 'Jamjodhpur'] },
      { name: 'Junagadh', cities: ['Junagadh', 'Veraval', 'Porbandar', 'Keshod', 'Mangrol'] },
      { name: 'Kutch', cities: ['Bhuj', 'Gandhidham', 'Mundra', 'Anjar', 'Mandvi'] },
      { name: 'Gandhinagar', cities: ['Gandhinagar', 'Mansa', 'Kalol', 'Dehgam'] },
      { name: 'Mehsana', cities: ['Mehsana', 'Patan', 'Visnagar', 'Kadi', 'Unjha'] },
      { name: 'Banaskantha', cities: ['Palanpur', 'Deesa', 'Danta', 'Tharad', 'Dhanera'] },
      { name: 'Sabarkantha', cities: ['Himmatnagar', 'Idar', 'Modasa', 'Prantij', 'Talod'] },
      { name: 'Panchmahal', cities: ['Godhra', 'Lunawada', 'Dahod', 'Halol', 'Kalol'] },
      { name: 'Kheda', cities: ['Nadiad', 'Anand', 'Borsad', 'Kapadwanj', 'Mehmedabad'] },
      { name: 'Amreli', cities: ['Amreli', 'Savarkundla', 'Rajula', 'Dhari', 'Lathi'] },
      { name: 'Navsari', cities: ['Navsari', 'Valsad', 'Bilimora', 'Chikhli', 'Gandevi'] },
    ],
  },
  {
    name: 'Haryana',
    districts: [
      { name: 'Faridabad', cities: ['Faridabad', 'Ballabhgarh', 'Palwal', 'Hodal'] },
      { name: 'Gurugram', cities: ['Gurugram', 'Manesar', 'Sohna', 'Pataudi', 'Farukhnagar'] },
      { name: 'Hisar', cities: ['Hisar', 'Hansi', 'Fatehabad', 'Barwala', 'Adampur'] },
      { name: 'Ambala', cities: ['Ambala', 'Ambala City', 'Naraingarh', 'Barara'] },
      { name: 'Karnal', cities: ['Karnal', 'Panipat', 'Kaithal', 'Assandh'] },
      { name: 'Rohtak', cities: ['Rohtak', 'Bahadurgarh', 'Jhajjar', 'Beri'] },
      { name: 'Sirsa', cities: ['Sirsa', 'Ellenabad', 'Dabwali', 'Rania'] },
      { name: 'Sonipat', cities: ['Sonipat', 'Gohana', 'Rai', 'Kharkhoda'] },
      { name: 'Yamunanagar', cities: ['Yamunanagar', 'Jagadhri', 'Radaur', 'Bilaspur'] },
      { name: 'Panchkula', cities: ['Panchkula', 'Kalka', 'Morni', 'Barwala'] },
      { name: 'Kurukshetra', cities: ['Kurukshetra', 'Thanesar', 'Pehowa', 'Shahabad'] },
      { name: 'Bhiwani', cities: ['Bhiwani', 'Charkhi Dadri', 'Loharu', 'Siwani'] },
      { name: 'Mahendragarh', cities: ['Narnaul', 'Mahendragarh', 'Ateli', 'Nangal Choudhary'] },
      { name: 'Rewari', cities: ['Rewari', 'Bawal', 'Dharuhera', 'Kosli'] },
      { name: 'Nuh', cities: ['Nuh', 'Tauru', 'Punhana', 'Ferozepur Jhirka'] },
    ],
  },
  {
    name: 'Himachal Pradesh',
    districts: [
      { name: 'Shimla', cities: ['Shimla', 'Rampur', 'Rohru', 'Theog', 'Jubbal'] },
      { name: 'Kangra', cities: ['Dharamsala', 'Palampur', 'Jawalamukhi', 'Dehra Gopipur', 'Nurpur'] },
      { name: 'Mandi', cities: ['Mandi', 'Sundarnagar', 'Jogindernagar', 'Karsog'] },
      { name: 'Kullu', cities: ['Kullu', 'Manali', 'Bhuntar', 'Banjar'] },
      { name: 'Solan', cities: ['Solan', 'Baddi', 'Nalagarh', 'Parwanoo', 'Kasauli'] },
      { name: 'Una', cities: ['Una', 'Amb', 'Gagret', 'Haroli'] },
      { name: 'Bilaspur', cities: ['Bilaspur', 'Ghumarwin', 'Swarghat', 'Namhol'] },
      { name: 'Hamirpur', cities: ['Hamirpur', 'Nadaun', 'Barsar', 'Sujanpur Tira'] },
      { name: 'Chamba', cities: ['Chamba', 'Dalhousie', 'Bhattiyat', 'Churah'] },
      { name: 'Sirmaur', cities: ['Nahan', 'Paonta Sahib', 'Rajgarh', 'Shillai'] },
      { name: 'Kinnaur', cities: ['Reckong Peo', 'Sangla', 'Kalpa', 'Nichar'] },
      { name: 'Lahaul and Spiti', cities: ['Keylong', 'Kaza', 'Udaipur', 'Manali'] },
    ],
  },
  {
    name: 'Jharkhand',
    districts: [
      { name: 'Ranchi', cities: ['Ranchi', 'Namkum', 'Hatia', 'Kanke'] },
      { name: 'Dhanbad', cities: ['Dhanbad', 'Jharia', 'Sindri', 'Baghmara'] },
      { name: 'Jamshedpur', cities: ['Jamshedpur', 'Jugsalai', 'Mango', 'Adityapur'] },
      { name: 'Bokaro', cities: ['Bokaro Steel City', 'Chas', 'Gomoh', 'Petarbar'] },
      { name: 'Hazaribagh', cities: ['Hazaribagh', 'Chatra', 'Barhi', 'Ichak'] },
      { name: 'Giridih', cities: ['Giridih', 'Deoghar', 'Jamtara', 'Madhupur'] },
      { name: 'Dumka', cities: ['Dumka', 'Pakur', 'Godda', 'Sahibganj'] },
      { name: 'Palamu', cities: ['Daltonganj', 'Hussainabad', 'Manatu', 'Satbarwa'] },
      { name: 'Garhwa', cities: ['Garhwa', 'Ranka', 'Nagar Untari', 'Bhandaria'] },
      { name: 'Lohardaga', cities: ['Lohardaga', 'Bhandra', 'Kisko', 'Kuru'] },
      { name: 'Simdega', cities: ['Simdega', 'Jaldega', 'Thethaitangar', 'Bano'] },
      { name: 'West Singhbhum', cities: ['Chaibasa', 'Chakradharpur', 'Baharagora', 'Jhinkpani'] },
    ],
  },
  {
    name: 'Karnataka',
    districts: [
      { name: 'Bengaluru Urban', cities: ['Bengaluru', 'Yelahanka', 'Rajajinagar', 'Whitefield', 'Electronic City'] },
      { name: 'Bengaluru Rural', cities: ['Devanahalli', 'Doddaballapur', 'Nelamangala', 'Hoskote'] },
      { name: 'Mysuru', cities: ['Mysuru', 'Nanjangud', 'Periyapatna', 'Hunsur', 'Krishnarajanagara'] },
      { name: 'Ballari', cities: ['Ballari', 'Hospet', 'Siruguppa', 'Sandur'] },
      { name: 'Belagavi', cities: ['Belagavi', 'Gokak', 'Mudhol', 'Chikodi', 'Bagalkot'] },
      { name: 'Hubballi-Dharwad', cities: ['Hubballi', 'Dharwad', 'Kundgol', 'Kalghatgi'] },
      { name: 'Mangaluru', cities: ['Mangaluru', 'Bantwal', 'Puttur', 'Sullia'] },
      { name: 'Kalaburagi', cities: ['Kalaburagi', 'Sedam', 'Yadgir', 'Raichur'] },
      { name: 'Shivamogga', cities: ['Shivamogga', 'Bhadravati', 'Sagar', 'Hosanagara'] },
      { name: 'Tumakuru', cities: ['Tumakuru', 'Tiptur', 'Pavagada', 'Madhugiri'] },
      { name: 'Davanagere', cities: ['Davanagere', 'Harihar', 'Harpanahalli', 'Jagalur'] },
      { name: 'Vijayapura', cities: ['Vijayapura', 'Sindgi', 'Basavana Bagevadi', 'Muddebihal'] },
      { name: 'Hassan', cities: ['Hassan', 'Belur', 'Arakalagud', 'Holenarasipur'] },
      { name: 'Raichur', cities: ['Raichur', 'Manvi', 'Devadurga', 'Sindhanur'] },
      { name: 'Udupi', cities: ['Udupi', 'Manipal', 'Kundapur', 'Karkala'] },
      { name: 'Chitradurga', cities: ['Chitradurga', 'Hiriyur', 'Challakere', 'Holalkere'] },
      { name: 'Kolar', cities: ['Kolar', 'Robertsonpet', 'Malur', 'Srinivaspura'] },
      { name: 'Mandya', cities: ['Mandya', 'Maddur', 'Pandavapura', 'Nagamangala'] },
      { name: 'Koppal', cities: ['Koppal', 'Gangavati', 'Yelburga', 'Kushtagi'] },
      { name: 'Gadag', cities: ['Gadag', 'Betgeri', 'Ron', 'Mundargi'] },
      { name: 'Bagalkot', cities: ['Bagalkot', 'Badami', 'Mudhol', 'Jamkhandi'] },
      { name: 'Haveri', cities: ['Haveri', 'Ranebennur', 'Byadagi', 'Hangal'] },
    ],
  },
  {
    name: 'Kerala',
    districts: [
      { name: 'Thiruvananthapuram', cities: ['Thiruvananthapuram', 'Neyyattinkara', 'Attingal', 'Varkala', 'Nedumangad'] },
      { name: 'Kollam', cities: ['Kollam', 'Paravur', 'Karunagappally', 'Kottarakkara', 'Punalur'] },
      { name: 'Pathanamthitta', cities: ['Pathanamthitta', 'Thiruvalla', 'Adoor', 'Pandalam', 'Ranni'] },
      { name: 'Alappuzha', cities: ['Alappuzha', 'Cherthala', 'Kayamkulam', 'Haripad', 'Mavelikkara'] },
      { name: 'Kottayam', cities: ['Kottayam', 'Changanassery', 'Ettumanoor', 'Pala', 'Thodupuzha'] },
      { name: 'Idukki', cities: ['Thodupuzha', 'Munnar', 'Kattappana', 'Adimali', 'Kumily'] },
      { name: 'Ernakulam', cities: ['Kochi', 'Aluva', 'Perumbavoor', 'Muvattupuzha', 'Angamaly'] },
      { name: 'Thrissur', cities: ['Thrissur', 'Chalakudy', 'Kodungallur', 'Irinjalakuda', 'Kunnamkulam'] },
      { name: 'Palakkad', cities: ['Palakkad', 'Ottapalam', 'Shoranur', 'Mannarkkad', 'Cherpulassery'] },
      { name: 'Malappuram', cities: ['Malappuram', 'Manjeri', 'Tirur', 'Perinthalmanna', 'Ponnani'] },
      { name: 'Kozhikode', cities: ['Kozhikode', 'Vadakara', 'Koyilandy', 'Feroke', 'Ramanattukara'] },
      { name: 'Wayanad', cities: ['Kalpetta', 'Mananthavady', 'Sulthan Bathery', 'Vythiri'] },
      { name: 'Kannur', cities: ['Kannur', 'Thalassery', 'Payyanur', 'Kuthuparamba', 'Mattannur'] },
      { name: 'Kasaragod', cities: ['Kasaragod', 'Kanhangad', 'Nileshwar', 'Hosdurg', 'Manjeshwar'] },
    ],
  },
  {
    name: 'Madhya Pradesh',
    districts: [
      { name: 'Bhopal', cities: ['Bhopal', 'Berasia', 'Mandideep', 'Obaidullaganj'] },
      { name: 'Indore', cities: ['Indore', 'Mhow', 'Sanwer', 'Depalpur', 'Hatod'] },
      { name: 'Jabalpur', cities: ['Jabalpur', 'Katni', 'Damoh', 'Patan', 'Sihora'] },
      { name: 'Gwalior', cities: ['Gwalior', 'Morena', 'Bhind', 'Dabra', 'Datia'] },
      { name: 'Ujjain', cities: ['Ujjain', 'Nagda', 'Khachrod', 'Barnagar', 'Tarana'] },
      { name: 'Sagar', cities: ['Sagar', 'Banda', 'Khurai', 'Rahatgarh', 'Rehli'] },
      { name: 'Rewa', cities: ['Rewa', 'Satna', 'Churhat', 'Mauganj', 'Sirmour'] },
      { name: 'Chhindwara', cities: ['Chhindwara', 'Sausar', 'Parasia', 'Amarwara'] },
      { name: 'Dewas', cities: ['Dewas', 'Sonkatch', 'Tonk Khurd', 'Bagli'] },
      { name: 'Ratlam', cities: ['Ratlam', 'Jaora', 'Sailana', 'Alot'] },
      { name: 'Sehore', cities: ['Sehore', 'Budhni', 'Ashta', 'Ichawar'] },
      { name: 'Hoshangabad', cities: ['Hoshangabad', 'Itarsi', 'Seoni Malwa', 'Babai'] },
      { name: 'Vidisha', cities: ['Vidisha', 'Ganj Basoda', 'Kurwai', 'Lateri'] },
      { name: 'Shajapur', cities: ['Shajapur', 'Shujalpur', 'Agar Malwa', 'Kalapipal'] },
      { name: 'Betul', cities: ['Betul', 'Amla', 'Multai', 'Sarni'] },
      { name: 'Dhar', cities: ['Dhar', 'Mhow', 'Kukshi', 'Badnawar'] },
      { name: 'Khargone', cities: ['Khargone', 'Barwaha', 'Bhikangaon', 'Kasrawad'] },
      { name: 'Khandwa', cities: ['Khandwa', 'Burhanpur', 'Harsud', 'Pandhana'] },
      { name: 'Morena', cities: ['Morena', 'Ambah', 'Sabalgarh', 'Porsa'] },
      { name: 'Shivpuri', cities: ['Shivpuri', 'Guna', 'Pichhore', 'Badarwas'] },
    ],
  },
  {
    name: 'Maharashtra',
    districts: [
      { name: 'Mumbai City', cities: ['Mumbai', 'Colaba', 'Bandra', 'Kurla', 'Dharavi'] },
      { name: 'Mumbai Suburban', cities: ['Borivali', 'Andheri', 'Malad', 'Kandivali', 'Goregaon'] },
      { name: 'Pune', cities: ['Pune', 'Pimpri-Chinchwad', 'Baramati', 'Talegaon', 'Lonavala'] },
      { name: 'Thane', cities: ['Thane', 'Navi Mumbai', 'Bhiwandi', 'Kalyan', 'Ulhasnagar'] },
      { name: 'Nashik', cities: ['Nashik', 'Malegaon', 'Igatpuri', 'Sinnar', 'Nandgaon'] },
      { name: 'Aurangabad', cities: ['Aurangabad', 'Jalna', 'Paithan', 'Gangapur', 'Kannad'] },
      { name: 'Solapur', cities: ['Solapur', 'Barshi', 'Osmanabad', 'Akkalkot', 'Pandharpur'] },
      { name: 'Nagpur', cities: ['Nagpur', 'Wardha', 'Hinganghat', 'Yavatmal', 'Wani'] },
      { name: 'Amravati', cities: ['Amravati', 'Achalpur', 'Chandur Bazar', 'Daryapur', 'Warud'] },
      { name: 'Kolhapur', cities: ['Kolhapur', 'Ichalkaranji', 'Jaysingpur', 'Kagal', 'Gadhinglaj'] },
      { name: 'Ratnagiri', cities: ['Ratnagiri', 'Chiplun', 'Rajapur', 'Dapoli', 'Sangameshwar'] },
      { name: 'Satara', cities: ['Satara', 'Karad', 'Phaltan', 'Wai', 'Mahabaleshwar'] },
      { name: 'Sangli', cities: ['Sangli', 'Miraj', 'Islampur', 'Vita', 'Shirala'] },
      { name: 'Latur', cities: ['Latur', 'Nanded', 'Udgir', 'Nilanga', 'Ausa'] },
      { name: 'Ahmednagar', cities: ['Ahmednagar', 'Shirdi', 'Shrirampur', 'Kopargaon', 'Sangamner'] },
      { name: 'Jalgaon', cities: ['Jalgaon', 'Bhusawal', 'Pachora', 'Chalisgaon', 'Chopda'] },
      { name: 'Dhule', cities: ['Dhule', 'Shirpur', 'Sindkheda', 'Sakri'] },
      { name: 'Chandrapur', cities: ['Chandrapur', 'Ballarpur', 'Warora', 'Bramhapuri', 'Gondpipri'] },
      { name: 'Beed', cities: ['Beed', 'Ambajogai', 'Ashti', 'Georai', 'Parli'] },
      { name: 'Palghar', cities: ['Palghar', 'Vasai', 'Virar', 'Boisar', 'Dahanu'] },
      { name: 'Raigad', cities: ['Alibag', 'Pen', 'Panvel', 'Uran', 'Karjat'] },
    ],
  },
  {
    name: 'Manipur',
    districts: [
      { name: 'Imphal West', cities: ['Imphal', 'Lamphelpat', 'Keishampat', 'Langjing'] },
      { name: 'Imphal East', cities: ['Porompat', 'Heingang', 'Thangmeiband', 'Irilbung'] },
      { name: 'Thoubal', cities: ['Thoubal', 'Wangbal', 'Kakching', 'Lilong'] },
      { name: 'Bishnupur', cities: ['Bishnupur', 'Moirang', 'Nambol', 'Kumbi'] },
      { name: 'Senapati', cities: ['Senapati', 'Mao', 'Paomata', 'Sadar Hills'] },
      { name: 'Churachandpur', cities: ['Churachandpur', 'Saikot', 'Tuibong', 'Henglep'] },
    ],
  },
  {
    name: 'Meghalaya',
    districts: [
      { name: 'East Khasi Hills', cities: ['Shillong', 'Cherrapunji', 'Mawsynram', 'Smit', 'Mairang'] },
      { name: 'West Khasi Hills', cities: ['Nongstoin', 'Mairang', 'Mawkyrwat', 'Ranikor'] },
      { name: 'Ri Bhoi', cities: ['Nongpoh', 'Umroi', 'Umsning', 'Bhoirymbong'] },
      { name: 'East Jaintia Hills', cities: ['Khliehriat', 'Lad Rymbai', 'Sutnga', 'Amlarem'] },
      { name: 'West Jaintia Hills', cities: ['Jowai', 'Shangpung', 'Thadlaskein'] },
      { name: 'East Garo Hills', cities: ['Williamnagar', 'Resubelpara', 'Songsak'] },
      { name: 'West Garo Hills', cities: ['Tura', 'Dalu', 'Phulbari', 'Selsella'] },
      { name: 'South Garo Hills', cities: ['Baghmara', 'Siju', 'Rongram'] },
    ],
  },
  {
    name: 'Mizoram',
    districts: [
      { name: 'Aizawl', cities: ['Aizawl', 'Durtlang', 'Zemabawk', 'Sairang'] },
      { name: 'Lunglei', cities: ['Lunglei', 'Tlabung', 'Lawngtlai', 'Demagiri'] },
      { name: 'Champhai', cities: ['Champhai', 'Khawzawl', 'Ngopa', 'Phullen'] },
      { name: 'Kolasib', cities: ['Kolasib', 'Bairabi', 'Thingdawl', 'Vairengte'] },
      { name: 'Serchhip', cities: ['Serchhip', 'Thenzawl', 'Buarpui', 'N. Vanlaiphai'] },
      { name: 'Mamit', cities: ['Mamit', 'West Phaileng', 'Zawlnuam'] },
    ],
  },
  {
    name: 'Nagaland',
    districts: [
      { name: 'Kohima', cities: ['Kohima', 'Zubza', 'Kigwema', 'Jotsoma'] },
      { name: 'Dimapur', cities: ['Dimapur', 'Chumukedima', 'Medziphema', 'Niuland'] },
      { name: 'Mokokchung', cities: ['Mokokchung', 'Tuli', 'Longleng', 'Ungma'] },
      { name: 'Wokha', cities: ['Wokha', 'Bhandari', 'Sanis', 'Englan'] },
      { name: 'Zunheboto', cities: ['Zunheboto', 'Akuluto', 'Suruhuto', 'Aghunato'] },
      { name: 'Tuensang', cities: ['Tuensang', 'Shamator', 'Noksen', 'Sangsangyu'] },
      { name: 'Mon', cities: ['Mon', 'Tizit', 'Aboi', 'Monyakshu'] },
      { name: 'Phek', cities: ['Phek', 'Pfutsero', 'Chizami', 'Meluri'] },
    ],
  },
  {
    name: 'Odisha',
    districts: [
      { name: 'Khordha', cities: ['Bhubaneswar', 'Puri', 'Khordha', 'Jatni', 'Balianta'] },
      { name: 'Cuttack', cities: ['Cuttack', 'Choudwar', 'Kendrapara', 'Jagatsinghpur', 'Athagarh'] },
      { name: 'Sambalpur', cities: ['Sambalpur', 'Burla', 'Hirakud', 'Jharsuguda'] },
      { name: 'Ganjam', cities: ['Berhampur', 'Gopalpur', 'Bhanjanagar', 'Phulbani'] },
      { name: 'Sundargarh', cities: ['Rourkela', 'Sundargarh', 'Bonai', 'Rajgangpur'] },
      { name: 'Balasore', cities: ['Balasore', 'Bhadrak', 'Jaleswar', 'Remuna'] },
      { name: 'Mayurbhanj', cities: ['Baripada', 'Jashipur', 'Rairangpur', 'Karanjia'] },
      { name: 'Angul', cities: ['Angul', 'Talcher', 'Dhenkanal', 'Athamallik'] },
      { name: 'Koraput', cities: ['Koraput', 'Jeypore', 'Sunabeda', 'Nabarangapur'] },
      { name: 'Kalahandi', cities: ['Bhawanipatna', 'Nawapara', 'Kesinga', 'Dharamgarh'] },
      { name: 'Bolangir', cities: ['Bolangir', 'Titlagarh', 'Kantabanji', 'Patnagarh'] },
      { name: 'Bargarh', cities: ['Bargarh', 'Padampur', 'Sohela', 'Barpali'] },
    ],
  },
  {
    name: 'Punjab',
    districts: [
      { name: 'Ludhiana', cities: ['Ludhiana', 'Jagraon', 'Khanna', 'Raikot', 'Doraha'] },
      { name: 'Amritsar', cities: ['Amritsar', 'Majitha', 'Ajnala', 'Baba Bakala', 'Tarn Taran'] },
      { name: 'Jalandhar', cities: ['Jalandhar', 'Nakodar', 'Phillaur', 'Adampur', 'Kartarpur'] },
      { name: 'Patiala', cities: ['Patiala', 'Rajpura', 'Nabha', 'Sangrur', 'Fatehgarh Sahib'] },
      { name: 'Mohali', cities: ['Mohali', 'Kharar', 'Derabassi', 'Dera Bassi', 'Zirakpur'] },
      { name: 'Bathinda', cities: ['Bathinda', 'Goniana', 'Rampura Phul', 'Talwandi Sabo'] },
      { name: 'Gurdaspur', cities: ['Gurdaspur', 'Pathankot', 'Batala', 'Dinanagar'] },
      { name: 'Hoshiarpur', cities: ['Hoshiarpur', 'Mukerian', 'Dasuya', 'Garhshankar'] },
      { name: 'Firozpur', cities: ['Firozpur', 'Fazilka', 'Zira', 'Jalalabad'] },
      { name: 'Fatehgarh Sahib', cities: ['Fatehgarh Sahib', 'Amloh', 'Bassi Pathana', 'Mandi Gobindgarh'] },
      { name: 'Rupnagar', cities: ['Rupnagar', 'Morinda', 'Anandpur Sahib', 'Nangal'] },
      { name: 'Kapurthala', cities: ['Kapurthala', 'Phagwara', 'Sultanpur Lodhi', 'Bhulath'] },
      { name: 'Sangrur', cities: ['Sangrur', 'Sunam', 'Malerkotla', 'Barnala'] },
    ],
  },
  {
    name: 'Rajasthan',
    districts: [
      { name: 'Jaipur', cities: ['Jaipur', 'Sanganer', 'Chomu', 'Kotputli', 'Shahpura'] },
      { name: 'Jodhpur', cities: ['Jodhpur', 'Pali', 'Sojat', 'Balotra', 'Bilara'] },
      { name: 'Kota', cities: ['Kota', 'Bundi', 'Baran', 'Jhalawar', 'Ramganj Mandi'] },
      { name: 'Udaipur', cities: ['Udaipur', 'Nathdwara', 'Rajsamand', 'Banswara', 'Dungarpur'] },
      { name: 'Ajmer', cities: ['Ajmer', 'Beawar', 'Kishangarh', 'Nasirabad', 'Kekri'] },
      { name: 'Bikaner', cities: ['Bikaner', 'Sriganganagar', 'Hanumangarh', 'Suratgarh', 'Anupgarh'] },
      { name: 'Bharatpur', cities: ['Bharatpur', 'Deeg', 'Kaman', 'Nagar', 'Weir'] },
      { name: 'Alwar', cities: ['Alwar', 'Behror', 'Rajgarh', 'Bansur', 'Tijara'] },
      { name: 'Sikar', cities: ['Sikar', 'Fatehpur', 'Laxmangarh', 'Neem Ka Thana', 'Srimadhopur'] },
      { name: 'Nagaur', cities: ['Nagaur', 'Merta City', 'Ladnun', 'Didwana', 'Nawa'] },
      { name: 'Jaisalmer', cities: ['Jaisalmer', 'Sam', 'Pokhran', 'Ramgarh'] },
      { name: 'Barmer', cities: ['Barmer', 'Balotra', 'Sheo', 'Gudamalani'] },
      { name: 'Jhunjhunu', cities: ['Jhunjhunu', 'Pilani', 'Chirawa', 'Surajgarh'] },
      { name: 'Churu', cities: ['Churu', 'Sardarshahar', 'Ratangarh', 'Sujangarh'] },
      { name: 'Dausa', cities: ['Dausa', 'Bandikui', 'Lalsot', 'Sikrai'] },
      { name: 'Sawai Madhopur', cities: ['Sawai Madhopur', 'Gangapur City', 'Hindaun', 'Bamanwas'] },
      { name: 'Tonk', cities: ['Tonk', 'Malpura', 'Niwai', 'Deoli'] },
      { name: 'Bundi', cities: ['Bundi', 'Nainwa', 'Indergarh', 'Keshoraipatan'] },
    ],
  },
  {
    name: 'Sikkim',
    districts: [
      { name: 'East Sikkim', cities: ['Gangtok', 'Rumtek', 'Ranipool', 'Pakyong'] },
      { name: 'West Sikkim', cities: ['Geyzing', 'Legship', 'Jorethang', 'Nayabazar'] },
      { name: 'North Sikkim', cities: ['Mangan', 'Chungthang', 'Lachen', 'Lachung'] },
      { name: 'South Sikkim', cities: ['Namchi', 'Ravangla', 'Jorethang', 'Temi'] },
      { name: 'Soreng', cities: ['Soreng', 'Dentam', 'Rinchenpong'] },
      { name: 'Pakyong', cities: ['Pakyong', 'Rongli', 'Rangpo', 'Dikchu'] },
    ],
  },
  {
    name: 'Tamil Nadu',
    districts: [
      { name: 'Chennai', cities: ['Chennai', 'Ambattur', 'Avadi', 'Tambaram', 'Porur'] },
      { name: 'Coimbatore', cities: ['Coimbatore', 'Tiruppur', 'Pollachi', 'Mettupalayam', 'Annur'] },
      { name: 'Madurai', cities: ['Madurai', 'Dindigul', 'Sivaganga', 'Ramanathapuram', 'Virudhunagar'] },
      { name: 'Salem', cities: ['Salem', 'Attur', 'Omalur', 'Mettur', 'Edappadi'] },
      { name: 'Tiruchirappalli', cities: ['Tiruchirappalli', 'Thanjavur', 'Kumbakonam', 'Karur', 'Ariyalur'] },
      { name: 'Tirunelveli', cities: ['Tirunelveli', 'Thoothukudi', 'Nagercoil', 'Palayamkottai', 'Valliyur'] },
      { name: 'Vellore', cities: ['Vellore', 'Ranipet', 'Arcot', 'Katpadi', 'Gudiyatham'] },
      { name: 'Erode', cities: ['Erode', 'Namakkal', 'Gobichettipalayam', 'Bhavani', 'Perundurai'] },
      { name: 'Tiruvannamalai', cities: ['Tiruvannamalai', 'Arni', 'Polur', 'Vandavasi', 'Cheyyar'] },
      { name: 'Kancheepuram', cities: ['Kancheepuram', 'Chengalpattu', 'Tambaram', 'Uthiramerur', 'Madurantakam'] },
      { name: 'Villupuram', cities: ['Villupuram', 'Tindivanam', 'Gingee', 'Kallakurichi', 'Sankarapuram'] },
      { name: 'Thanjavur', cities: ['Thanjavur', 'Kumbakonam', 'Papanasam', 'Pattukottai', 'Peravurani'] },
      { name: 'Nagapattinam', cities: ['Nagapattinam', 'Vedaranyam', 'Mayiladuthurai', 'Sirkazhi'] },
      { name: 'Dharmapuri', cities: ['Dharmapuri', 'Hosur', 'Krishnagiri', 'Palacode', 'Harur'] },
      { name: 'Nilgiris', cities: ['Ooty', 'Coonoor', 'Kotagiri', 'Gudalur'] },
    ],
  },
  {
    name: 'Telangana',
    districts: [
      { name: 'Hyderabad', cities: ['Hyderabad', 'Secunderabad', 'Uppal', 'LB Nagar', 'Kukatpally'] },
      { name: 'Rangareddy', cities: ['Shadnagar', 'Chevella', 'Mahbubnagar', 'Vikarabad', 'Tandur'] },
      { name: 'Medchal-Malkajgiri', cities: ['Medchal', 'Malkajgiri', 'Keesara', 'Ghatkesar', 'Dundigal'] },
      { name: 'Warangal Urban', cities: ['Warangal', 'Kazipet', 'Hanamkonda', 'Parkal', 'Narsampet'] },
      { name: 'Karimnagar', cities: ['Karimnagar', 'Peddapalli', 'Jagtial', 'Ramagundam', 'Huzurabad'] },
      { name: 'Nizamabad', cities: ['Nizamabad', 'Armoor', 'Bodhan', 'Kamareddy', 'Banswada'] },
      { name: 'Khammam', cities: ['Khammam', 'Kothagudem', 'Bhadrachalam', 'Palwancha', 'Yellandu'] },
      { name: 'Nalgonda', cities: ['Nalgonda', 'Suryapet', 'Miryalaguda', 'Nagarjunasagar', 'Bhongir'] },
      { name: 'Mahabubnagar', cities: ['Mahabubnagar', 'Wanaparthy', 'Jadcherla', 'Narayanpet', 'Gadwal'] },
      { name: 'Adilabad', cities: ['Adilabad', 'Mancherial', 'Nirmal', 'Bhainsa', 'Utnoor'] },
      { name: 'Siddipet', cities: ['Siddipet', 'Gajwel', 'Dubbaka', 'Husnabad'] },
      { name: 'Sangareddy', cities: ['Sangareddy', 'Patancheru', 'Zaheerabad', 'Sadasivpet'] },
    ],
  },
  {
    name: 'Tripura',
    districts: [
      { name: 'West Tripura', cities: ['Agartala', 'Bishalgarh', 'Melaghar', 'Jirania'] },
      { name: 'Sepahijala', cities: ['Bishramganj', 'Sonamura', 'Boxanagar'] },
      { name: 'Khowai', cities: ['Khowai', 'Teliamura', 'Kalyanpur'] },
      { name: 'South Tripura', cities: ['Udaipur', 'Belonia', 'Sabroom', 'Santirbazar'] },
      { name: 'Gomati', cities: ['Udaipur', 'Amarpur', 'Garjee'] },
      { name: 'Unakoti', cities: ['Kailashahar', 'Kumarghat', 'Chandipur'] },
      { name: 'North Tripura', cities: ['Dharmanagar', 'Panisagar', 'Jubarajnagar'] },
      { name: 'Dhalai', cities: ['Ambassa', 'Kamalpur', 'Gandacherra'] },
    ],
  },
  {
    name: 'Uttar Pradesh',
    districts: [
      { name: 'Lucknow', cities: ['Lucknow', 'Aliganj', 'Chinhat', 'Malihabad', 'Bakshi Ka Talab'] },
      { name: 'Kanpur Nagar', cities: ['Kanpur', 'Unnao', 'Bithur', 'Maharajpur', 'Kalyanpur'] },
      { name: 'Agra', cities: ['Agra', 'Firozabad', 'Mathura', 'Hathras', 'Etah'] },
      { name: 'Varanasi', cities: ['Varanasi', 'Mirzapur', 'Chandauli', 'Ghazipur', 'Jaunpur'] },
      { name: 'Prayagraj', cities: ['Prayagraj', 'Kaushambi', 'Pratapgarh', 'Fatehpur', 'Raebareli'] },
      { name: 'Meerut', cities: ['Meerut', 'Hapur', 'Ghaziabad', 'Noida', 'Bulandshahr'] },
      { name: 'Bareilly', cities: ['Bareilly', 'Badaun', 'Shahjahanpur', 'Pilibhit', 'Rampur'] },
      { name: 'Aligarh', cities: ['Aligarh', 'Hathras', 'Kasganj', 'Etah', 'Mahamaya Nagar'] },
      { name: 'Moradabad', cities: ['Moradabad', 'Amroha', 'Sambhal', 'Bijnor', 'Rampur'] },
      { name: 'Gorakhpur', cities: ['Gorakhpur', 'Deoria', 'Kushinagar', 'Maharajganj', 'Sant Kabir Nagar'] },
      { name: 'Gautam Buddha Nagar', cities: ['Noida', 'Greater Noida', 'Dadri', 'Jewar'] },
      { name: 'Ghaziabad', cities: ['Ghaziabad', 'Loni', 'Hapur', 'Modi Nagar', 'Pilkhuwa'] },
      { name: 'Muzaffarnagar', cities: ['Muzaffarnagar', 'Shamli', 'Kairana', 'Budhana'] },
      { name: 'Saharanpur', cities: ['Saharanpur', 'Deoband', 'Nakur', 'Rampur Maniharan'] },
      { name: 'Mathura', cities: ['Mathura', 'Vrindavan', 'Govardhan', 'Barsana', 'Nandgaon'] },
      { name: 'Ayodhya', cities: ['Ayodhya', 'Faizabad', 'Bikapur', 'Tanda', 'Sohawal'] },
      { name: 'Sultanpur', cities: ['Sultanpur', 'Amethi', 'Gauriganj', 'Musafirkhana'] },
      { name: 'Azamgarh', cities: ['Azamgarh', 'Mau', 'Ballia', 'Ghosi', 'Lalganj'] },
      { name: 'Allahabad', cities: ['Prayagraj', 'Phulpur', 'Handia', 'Meja', 'Karchana'] },
      { name: 'Jhansi', cities: ['Jhansi', 'Lalitpur', 'Mauranipur', 'Moth', 'Barwa Sagar'] },
      { name: 'Banda', cities: ['Banda', 'Chitrakoot', 'Hamirpur', 'Mahoba', 'Mau'] },
    ],
  },
  {
    name: 'Uttarakhand',
    districts: [
      { name: 'Dehradun', cities: ['Dehradun', 'Mussoorie', 'Rishikesh', 'Doiwala', 'Vikasnagar'] },
      { name: 'Haridwar', cities: ['Haridwar', 'Roorkee', 'Manglaur', 'Laksar', 'Jwalapur'] },
      { name: 'Nainital', cities: ['Nainital', 'Haldwani', 'Ramnagar', 'Kaladhungi', 'Bhimtal'] },
      { name: 'Udham Singh Nagar', cities: ['Rudrapur', 'Kashipur', 'Khatima', 'Jaspur', 'Bazpur'] },
      { name: 'Almora', cities: ['Almora', 'Ranikhet', 'Bhikiyasain', 'Dwarahat', 'Sult'] },
      { name: 'Pauri Garhwal', cities: ['Pauri', 'Srinagar', 'Kotdwar', 'Dugadda', 'Lansdowne'] },
      { name: 'Tehri Garhwal', cities: ['Tehri', 'New Tehri', 'Chamba', 'Dhanaulti', 'Ghansali'] },
      { name: 'Uttarkashi', cities: ['Uttarkashi', 'Barkot', 'Purola', 'Bhatwari'] },
      { name: 'Chamoli', cities: ['Gopeshwar', 'Joshimath', 'Karnaprayag', 'Nandprayag'] },
      { name: 'Rudraprayag', cities: ['Rudraprayag', 'Agastyamuni', 'Ukhimath', 'Tilwara'] },
      { name: 'Bageshwar', cities: ['Bageshwar', 'Kapkot', 'Garud', 'Kanda'] },
      { name: 'Pithoragarh', cities: ['Pithoragarh', 'Dharchula', 'Didihat', 'Berinag'] },
      { name: 'Champawat', cities: ['Champawat', 'Lohaghat', 'Tanakpur', 'Pati'] },
    ],
  },
  {
    name: 'West Bengal',
    districts: [
      { name: 'Kolkata', cities: ['Kolkata', 'Howrah', 'Salt Lake City', 'New Town', 'Behala'] },
      { name: 'North 24 Parganas', cities: ['Barasat', 'Barrackpore', 'Basirhat', 'Bongaon', 'Habra'] },
      { name: 'South 24 Parganas', cities: ['Alipore', 'Budge Budge', 'Diamond Harbour', 'Baruipur', 'Kakdwip'] },
      { name: 'Hooghly', cities: ['Chandannagar', 'Serampore', 'Rishra', 'Uttarpara', 'Arambagh'] },
      { name: 'Burdwan', cities: ['Asansol', 'Durgapur', 'Burdwan', 'Kulti', 'Raniganj'] },
      { name: 'Murshidabad', cities: ['Berhampore', 'Jangipur', 'Dhulian', 'Jiaganj', 'Lalbagh'] },
      { name: 'Nadia', cities: ['Krishnanagar', 'Nabadwip', 'Ranaghat', 'Santipur', 'Chakdaha'] },
      { name: 'Malda', cities: ['Malda', 'English Bazar', 'Old Malda', 'Gajole', 'Chanchal'] },
      { name: 'Birbhum', cities: ['Suri', 'Rampurhat', 'Bolpur', 'Sainthia', 'Nalhati'] },
      { name: 'Bankura', cities: ['Bankura', 'Bishnupur', 'Sonamukhi', 'Khatra', 'Barjora'] },
      { name: 'Purulia', cities: ['Purulia', 'Jhalda', 'Raghunathpur', 'Adra', 'Manbazar'] },
      { name: 'Jalpaiguri', cities: ['Jalpaiguri', 'Siliguri', 'Mal', 'Dhupguri', 'Raiganj'] },
      { name: 'Darjeeling', cities: ['Darjeeling', 'Kurseong', 'Kalimpong', 'Siliguri', 'Mirik'] },
      { name: 'Cooch Behar', cities: ['Cooch Behar', 'Mathabhanga', 'Tufanganj', 'Dinhata'] },
      { name: 'Alipurduar', cities: ['Alipurduar', 'Hasimara', 'Birpara', 'Falakata'] },
      { name: 'Medinipur', cities: ['Midnapore', 'Kharagpur', 'Jhargram', 'Ghatal', 'Tamluk'] },
    ],
  },
  {
    name: 'Andaman and Nicobar Islands',
    districts: [
      { name: 'South Andaman', cities: ['Port Blair', 'Aberdeen Bazar', 'Buniyadabad'] },
      { name: 'North and Middle Andaman', cities: ['Mayabunder', 'Diglipur', 'Rangat'] },
      { name: 'Nicobar', cities: ['Car Nicobar', 'Nancowry', 'Campbellabad'] },
    ],
  },
  {
    name: 'Chandigarh',
    districts: [
      { name: 'Chandigarh', cities: ['Chandigarh', 'Manimajra', 'Burail', 'Dhanas'] },
    ],
  },
  {
    name: 'Dadra and Nagar Haveli and Daman and Diu',
    districts: [
      { name: 'Dadra and Nagar Haveli', cities: ['Silvassa', 'Amli', 'Piparia', 'Dadra'] },
      { name: 'Daman', cities: ['Daman', 'Nani Daman', 'Moti Daman'] },
      { name: 'Diu', cities: ['Diu', 'Ghoghla', 'Vanakbara'] },
    ],
  },
  {
    name: 'Delhi',
    districts: [
      { name: 'Central Delhi', cities: ['Connaught Place', 'Paharganj', 'Karol Bagh', 'Sadar Bazar'] },
      { name: 'East Delhi', cities: ['Preet Vihar', 'Mayur Vihar', 'Shahdara', 'Vivek Vihar'] },
      { name: 'New Delhi', cities: ['New Delhi', 'Chanakyapuri', 'Sarojini Nagar', 'RK Puram'] },
      { name: 'North Delhi', cities: ['Civil Lines', 'Model Town', 'Burari', 'Jahangirpuri'] },
      { name: 'North East Delhi', cities: ['Seelampur', 'Welcome Colony', 'Mustafabad', 'Bhajanpura'] },
      { name: 'North West Delhi', cities: ['Rohini', 'Pitampura', 'Shalimar Bagh', 'Ashok Vihar'] },
      { name: 'Shahdara', cities: ['Shahdara', 'Seemapuri', 'Nand Nagri', 'Ghonda'] },
      { name: 'South Delhi', cities: ['Saket', 'Hauz Khas', 'Lajpat Nagar', 'Malviya Nagar'] },
      { name: 'South East Delhi', cities: ['Okhla', 'Jamia Nagar', 'Badarpur', 'Tughlakabad'] },
      { name: 'South West Delhi', cities: ['Dwarka', 'Palam', 'Vasant Kunj', 'Mahipalpur'] },
      { name: 'West Delhi', cities: ['Janakpuri', 'Vikaspuri', 'Uttam Nagar', 'Tilak Nagar'] },
    ],
  },
  {
    name: 'Jammu and Kashmir',
    districts: [
      { name: 'Jammu', cities: ['Jammu', 'Samba', 'Bishnah', 'Akhnoor', 'Nagrota'] },
      { name: 'Srinagar', cities: ['Srinagar', 'Budgam', 'Chadoora', 'Pampore'] },
      { name: 'Anantnag', cities: ['Anantnag', 'Bijbehara', 'Kokernag', 'Qazigund'] },
      { name: 'Baramulla', cities: ['Baramulla', 'Sopore', 'Uri', 'Pattan', 'Kupwara'] },
      { name: 'Pulwama', cities: ['Pulwama', 'Pampore', 'Awantipora', 'Tral'] },
      { name: 'Rajouri', cities: ['Rajouri', 'Nowshera', 'Thanamandi', 'Kalakote'] },
      { name: 'Udhampur', cities: ['Udhampur', 'Ramnagar', 'Chenani', 'Dooru'] },
      { name: 'Kathua', cities: ['Kathua', 'Hiranagar', 'Basholi', 'Billawar'] },
      { name: 'Kupwara', cities: ['Kupwara', 'Handwara', 'Lolab', 'Karnah'] },
      { name: 'Kulgam', cities: ['Kulgam', 'Devsar', 'Frisal', 'D H Pora'] },
    ],
  },
  {
    name: 'Ladakh',
    districts: [
      { name: 'Leh', cities: ['Leh', 'Kargil', 'Nubra', 'Zanskar'] },
      { name: 'Kargil', cities: ['Kargil', 'Drass', 'Sankoo', 'Zanskar'] },
    ],
  },
  {
    name: 'Lakshadweep',
    districts: [
      { name: 'Lakshadweep', cities: ['Kavaratti', 'Agatti', 'Andrott', 'Kalpeni', 'Minicoy'] },
    ],
  },
  {
    name: 'Puducherry',
    districts: [
      { name: 'Puducherry', cities: ['Puducherry', 'Villianur', 'Ariyankuppam', 'Ozhukarai'] },
      { name: 'Karaikal', cities: ['Karaikal', 'Thirunallar', 'Neravy'] },
      { name: 'Mahe', cities: ['Mahe', 'Palloor', 'Chaliyam'] },
      { name: 'Yanam', cities: ['Yanam', 'Molletivaripalem', 'Coringa'] },
    ],
  },
];

export const STATE_NAMES = INDIA_LOCATIONS.map((s) => s.name);

export function getDistricts(stateName: string): District[] {
  return INDIA_LOCATIONS.find((s) => s.name === stateName)?.districts ?? [];
}

export function getCities(stateName: string, districtName: string): string[] {
  const state = INDIA_LOCATIONS.find((s) => s.name === stateName);
  return state?.districts.find((d) => d.name === districtName)?.cities ?? [];
}
